apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanbarn-web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: spanbarn-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spanbarn-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spanbarn-web
          image: ghcr.io/wiebe-xyz/spanbarn/web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
