apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - deployment-ingest.yaml
  - service-ingest.yaml
  - deployment-web.yaml
  - service-web.yaml
  - deployment-redis.yaml
  - service-redis.yaml
  - configmap.yaml
  - pvc.yaml
  - service-reads.yaml
