apiVersion: v1
kind: PersistentVolume
metadata:
  name: spanbarn-data-storage
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: spanbarn-local
  local:
    path: /mnt/storage/spanbarn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - layer7-prod
