apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spanbarn-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: spanbarn-local
  volumeName: spanbarn-data-storage
  resources:
    requests:
      storage: 500Gi
