apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanbarn
spec:
  template:
    spec:
      priorityClassName: spanbarn-staging
      containers:
        - name: spanbarn
          resources:
            requests:
              cpu: 50m
