apiVersion: ENC[AES256_GCM,data:5z8=,iv:d2/5wUbeccyJcKcD+A6RsQiCwFDk8pu9Mdhz5O8KWO8=,tag:n9g47DMkYgcKVZeaD4026Q==,type:str]
kind: ENC[AES256_GCM,data:4iqAvZNR,iv:6gdjn3tiPal32/G7ekOlAlBSOh1XXSirvHVrYnrP0P4=,tag:4PoVXsbeurkyJPsU+eO7nQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uepPjhII3bBJ874EWaNbXA==,iv:4pmFBtL4RDhJNJg+ksz2n98k/VZnQ42HCxOf0NRIhc0=,tag:WZZvg2bWiQtUTOauDfUu7Q==,type:str]
    namespace: ENC[AES256_GCM,data:v/xuQNrvoWNej7dKZfijrQ==,iv:IDx2w/HmHtgYmHSoSJi7onRuCMhq6+310y1BHFCs/dw=,tag:wnKCbbGaAdbRUKucEJMKTw==,type:str]
type: ENC[AES256_GCM,data:ItoqTO7k,iv:+nAFXungNgUziZDRyyQucfEQquYv4WMMvtAEO5cWm1U=,tag:lV7OKot14okB8ccCN2dyFQ==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:xDuX9DUU7CSKiuNq4J2Z9ss47Rnr1vnGmkLcVZCuenaGtY2A79ZdJw==,iv:pd5tPdsTwZPYvYbEyXiVr1lwPg1OkPhk9lwK8R7VzUA=,tag:g1zCY2PUZFh3GaoZTBpEGA==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:Qj0jGCM/r++cf1dX7IP+YDiONVusyswxNTYwALFG2AJpmO/Kz9I4qNQLMSzaOkaCTFP7WM+5aboQW8DVwzuAqg==,iv:kmQcy1tq4neotAbg7HYaLfLo3fSmaX3i82gd7G17Whg=,tag:Qb8XV1RILwSVvOW1/kqbCw==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:T8Ke+h7rLqnqKFUBpPu1iDUbMzxMqeBy3U+9o4179lgqwskuxGWE6A==,iv:gqK3K8pj243jve92fCVg9a5FsHjtRoyIsDZzfhVSpe0=,tag:KMTCfknGXU7gump7sfqVzg==,type:str]
    SPANBARN_SELF_API_KEY: ENC[AES256_GCM,data:xpX3lnnIbzrHe/RIDPUN8vlDYRacLCrPCteTpYUi5nf2jHCHikuIZg==,iv:Kv6xhijVqKOcUIkUDFynvZR+rQ4TbUjSGVry3g6+ZP0=,tag:YSZbb+nKmB2aSSR0nRDN8A==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:2WQaGYCF+A==,iv:4vLUnZVQtuJ5o6Dbh5NAHIU4ihh/3MGRmqxNocpfbu4=,tag:tGWOio23NYzST7rfm7cVHQ==,type:str]
    SPANBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:L09D97I=,iv:QxVRbvr1Ywx/hk1Pqeys2uExwURxVn35W6o6VeKf74s=,tag:wUOhyhgzATbaJ5Olm/RAaA==,type:str]
    SPANBARN_ADMIN_PASSWORD: ENC[AES256_GCM,data:1SvhRkG58XU=,iv:T8f9heYMCmf9DJq+z01AIsntSyic9+WhQYE6AVMPlJA=,tag:iaWhV4alk+vzgyXXVQwT4w==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:aXPpfVNZgbRXeN1gTua6ipqkS5JI,iv:590E9mIogLSARPGkOQitA4sMglPqSQ582oKgyOzWWPY=,tag:iEyVYbusJ3osiUCBfTr7Eg==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xBp+ejem2UTGWcAEzpKIeNXR8SCs,iv:qHi7DKD9OJZjqkqfDxYCFX8yDzEyAME59sC9i1zGdyE=,tag:vG0qH+eCqtb4SRkaV1IsiQ==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:4smw5MTMK+c2t5qkBPXbb4NGtvQA,iv:MjCbB4k/JSnfCz9qTgTXrkUBaLu2H/juwbAQMzQ5jos=,tag:b0qHQNzLS0SDN+uDSckdSw==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VDQvcHZmaWttSnJqMHNm
            TmxqWCt3eUVYcU5zSWRsM2p5N3BzMFI1c3dRCkdYblUyZHR5dVAxbDVtUXBQS0Y4
            ZHgxeTdQbDlUc05JdEtPbjlOQmF0RlUKLS0tIERTUnZLT1I1aWZCczFTeWoyWnBH
            ZmVmRGdGK2dkSllCRW5aeXg4Q0VtdkkKKUbzoLFtHJrxa0rxV0GOJFbcp5JEE0xY
            +3+cvNnbxZcy7HhLY1OzJZ6UmPbZ6XXWSDyQ6lqLFgo2SrrlcT8XGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T09:30:04Z"
    mac: ENC[AES256_GCM,data:8Y2E7rVwDAOpaCgzlniv/C12PE9CVT0oChV6sVtjWKsIbGmn/KDZeY4JD0PvSVbRlSiNhVcbOrOFQeo51Z2HrO0Bo3N/AD8CsuJ+5KaQax8untr36Qnu5nWJovRul1OKfVEMx36AglDgkURkye3BiGKvjig6UR+BgC4iGEnlbt4=,iv:GjgRvxG6YjAV1MM3vYQ/f6KupO7frIkYo08P4JiWC5c=,tag:n7MWaFsdc7aU/qQuEiMkJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
