apiVersion: ENC[AES256_GCM,data:/84=,iv:qJgDVNzeDxbH7PksQtkixS+lKT2raSfRFpoa2zlr56g=,tag:/sQAMDp3f3wV85zlBiHUsw==,type:str]
kind: ENC[AES256_GCM,data:eBPq/6gk,iv:B5u8li6bXvZcZ3cXSBbku1LE/8KMkaITJ/3zzEJit1M=,tag:MZsZ1IsBUdRteRpVkHnB/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qxna/zeKQBYKcV26/p0s8w==,iv:oLNcMSqpP8T+GRyyxZYc8tymkqbrmPpuE8geoF/ZQ2k=,tag:kLm9HRCmcvE1XXaXyJzcJg==,type:str]
    namespace: ENC[AES256_GCM,data:wxic4T+jg7gxmjVhigTZ9Q==,iv:HEbnlULwbdBkqNGN+Ro3I2sKc4gRZfg1Iq/gn8vEXC4=,tag:BNh7WEZ3btsvojr/ZFVpmQ==,type:str]
type: ENC[AES256_GCM,data:EwIZ8JhQ,iv:WMy2nMdS9vN3PWbdaX07hRfBp4rITrBSrrHuYhNFljU=,tag:/t/CVl327wIpk+VK/HOwQA==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:lPM/TWSlKrL0qcDrxsCI4m/u6nXgpLI/4Hpu8Lf3JmjN6FuRIDyVHA==,iv:oa8P2/UlXNvjfvhDv4FNt+XL0U3tMYiaeSyASmCFK/0=,tag:7ZKjPmUQVXI4IvemE8/w9A==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:SaUSyKuVMoRGb/Tw1mRa9lHfHuWH8lL53wSeyDvCo8G1wBuddV4ANSOpGSqXD7y/6EbVG89nyQsifgW+i2rhRg==,iv:ZxqileulggFIupdsNXz/d6DGWoXUmiVJjYMSW9/OwwA=,tag:G7XL0jxYOGlQD3AikURNqw==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:N/z/Z4oiQ5oBJ9+gDA66DIXRg1tDCl5V4Yjh0aIKcihG8Av3N40AEA==,iv:zOutZ6O1CEP4/9pRH2rhOIJW5PrLiq1/4bYOAV/H7mY=,tag:gYqM8X14WoE7BQWTsJ6xOg==,type:str]
    SPANBARN_SELF_API_KEY: ENC[AES256_GCM,data:CS4QBVtf+bNK6SVw+NLIpU/xRQ7ThzvPgAtGudGFY//WsVB4kmxzUQ==,iv:dou9d8dcOX08m1+TXJ3bt/JJKE+obZl4rYHSpvd+p6I=,tag:M4humSByyJ3WooVrMCCbDw==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:yapW6QVpvw==,iv:oKX9Sn90LR6pbdQCtGf1zd/dCVyrk4Had8eGvcVf8eU=,tag:QFxN7S3KW6jZ5bQyuiIRnw==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:/HxhnktMMXSeIZkUQP3tmmWuv3xa,iv:wP9+9sPHBtQouT8gwgj1eipNJhAXkBi58gXvjqzIoIc=,tag:C9UsjVUwhzdE8XeZacfjXA==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0yLGv0W8L52t7BHNVmeN9zlEq5HB,iv:dwU6phB9tAnCFxTOeTfdiDK/kGHgx/9qWnih73SmLNU=,tag:pP8pZU5br9GqQS195zRPPQ==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:nqFhmIaApEY7sUFtyphzCiMnZInQ,iv:Ozvrr2FLk9FbcLVybUeh2LH8bW4/EB3j+SUw1vnxtb0=,tag:BzokFyloN/hRqbaE/Wja1A==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZXl5Q2dDOUg4NjVxVWU4
            TmxFYzd1Q0lsa0N4VE1mbHNqckxRUjlZTXpzCmxsYWJqUFRyTkVVT0NSU1JYQXVE
            anBub3lRbEorMHp0YVJnTGVKWFErelUKLS0tIEhpMkU2a2crYVRVWUtnVjZiUzIz
            WkVwZi9ZYkh4ckI1YXF3K0NxVHUrakUKEhYW49afJFC88pDMJtRCryerhqUPtgEX
            tam2wc6rTs0PkEzFyPLaOMraQrTXe3KLZGtnhPWa87x7ILBWqMvWxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T06:40:27Z"
    mac: ENC[AES256_GCM,data:GQw9lMN7fP0ybnik8Koq2rHETPMeQOz+5UHJ/urUJrdZnD8iMG3Ijt+dR9b9am5TfYdEhq2c99H5UbVNIpW5JNbkZWPPWx/cf5KXGFJDGQmCgM6lSvmk7MleiUwk4Epv9At3kLU1xdr3HmfFRXlhsqYomTOa377QC8yRS4/+2JA=,iv:9I1w4qZ20NR9mHjpPefZYsR6/MXQMMtt7peEYHvUQto=,tag:z4Lm9k4RB6PHsuxZLDAP/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
