apiVersion: ENC[AES256_GCM,data:dao=,iv:+97hrobcLODXHVRpHwj8lqEY89PHKgYvEJG2IaDh30s=,tag:jHGvXWdMHjQIQgXL00mSvQ==,type:str]
kind: ENC[AES256_GCM,data:3zC8xjpE,iv:mGT7LDM/yY+d+SmSJp4Za322Q4HT+RuOBMJDl28pE40=,tag:J1Z+8draTMi+AOXsgOhEBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dd+83ah/NSAc1voeIJ7nvA==,iv:lbJ1eIVCoCwYgbsQBaNMJPluCkKTBFB1Nm3KG34YNbw=,tag:WVcKnK7vIj4fv3jx78hW4Q==,type:str]
    namespace: ENC[AES256_GCM,data:eX+Onaz2P13vhaJuJvAJRQ==,iv:0ulPogAMox5wLSmfxZpdvaDUkD+RMWGKx6Lo/OVNUeo=,tag:qE/5fvDyacxnt/dQFhhzBw==,type:str]
type: ENC[AES256_GCM,data:NmHf0fe/,iv:vf+eZ+lxRH50tCTq1xb+F/+N/XPX8+lEZC+Z8RsWnxM=,tag:UZsbcX9gWNC4OL4x9FdDUw==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:NCMPKB/WDdcRXa9haipdWpE7Nu0pqKq89j2EEmSlOkZZBWnsJbU+tw==,iv:bfnM/71hCrErsVem7tzBE2Eoz+bV1ynaen4ST4OJGcc=,tag:5V/3cNogNvCfJy4Uxte+0w==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:Ug7NaqLNTP9+vVUeyTlIuyix+1TFjX2qBeNZYv7u2IjIAMWVsmJJmcLpA577yVhOE5Uz3Xlk9d+mwSGmgIJMBA==,iv:tGEzNiJSDcXRg2bhU6wvi0zwoo18LlHSWZeZiX0VP68=,tag:Jeg6gvQSJAFo4lSnhRO7WA==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:bBrzw4aadxojbpUaMMr/e8aDlH5Id5Byb41l3dsZW5s5G6LTZvaPeA==,iv:yDsCf+S0p/KaAA0MO+y31GMmelVodX0Ry1THBuVo6js=,tag:bZX3KEdST0TEuVXXcavaIg==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:edaO8juLOg==,iv:QB3oIr96xHPXKZCkJs2jaPtIvgnH0FGgBzD8YOjj39k=,tag:YYOT6Oqfi0bLvu3/5NaQaQ==,type:str]
    SPANBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:A5gvdeU=,iv:3coX72Qk5+RWvTsN7d/7rq586yX/H+gKSImj197iLPk=,tag:KB9d/zWK1s2BcBFJnmM8HA==,type:str]
    SPANBARN_ADMIN_PASSWORD: ENC[AES256_GCM,data:9Pv49G9MxZU=,iv:wxquaEftUElUyc0HvCbGXJ2NNwMxvx4TTTGNwZNy3Gk=,tag:ZbVnJkzzAGaFh/SiCeD/zA==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:0mH2iheIhxU9pdAUtAZNzkQF94k3,iv:D6cTY4aGPYuSpPfItdfrHz5ar9evYJ1zCPMQO/67erk=,tag:y1RqgE9HpJopQmRIHZVUWA==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZKHcSZUynQ3kHacM39m7+5yfXLtP,iv:1eXumHWSD7tBJz3KZ+p5T1x0emaWOQbpaYIDQ85SOU8=,tag:5zEctiaSxylOEjWEHlcolg==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:BaATHLJHN1YMV464ZqhJEUgoKdgh,iv:vgEz5GcW4y6FWYKcU66crBO6vvR77ZKdnoi9ZP+U+B4=,tag:8ckmgQlmg5Anyc3a62scgg==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMjZNYzlwVUg1QWs0MnQz
            Z3Zra21qVkJxUlRDb1JOcUN2MGFpSy9HTEJVCnJwZHBKUUh4SStNZDIxQ2syTGRI
            YnQvOE8zaXV4aUZHWTVwUjFLZS9DYW8KLS0tIG52WWtTUEdHWThRdG1YZys5eXF6
            cjBqMWlpSGh0ZVZwTDJBc1hxTWhVS28KVRrcFG8BqBGNdIsh+y2ZgyWDmQymR0xM
            myQ0EQVDPn5O8j5f28JEprlUMsUkKgYMit3GnXTulfSC11njYbvoNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T14:09:38Z"
    mac: ENC[AES256_GCM,data:okqlCU3Ial3MFr7JR8HUEncPWsUwMx7j7ENTzqipY2w3gz1FVIcvJ6YB6Ez368nIgm6j3ubSFlyXcvlBCgIC3MkfCARPewVKAuxfv+yqbpIQc1wA3yFoYTntIkteocfFEuyKfmSF9RDzVxkYeXRH0uohHZR1sqpeF+2FYmvOxYw=,iv:x5OmCdTYsb4HkGHoFQnMd+nn5wmC3H+hNHleay0JGGc=,tag:OVJmzAKIFOquDOeWi96Nfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
