dbs:
  - path: /var/lib/spanbarn/spanbarn.db
    replicas:
      - type: s3
        bucket: spanbarn-sqlite
        path: ${LITESTREAM_REPLICA_PATH}
        endpoint: https://s3.wiebe.xyz
        force-path-style: true
        access-key-id: ${LITESTREAM_ACCESS_KEY_ID}
        secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}
        retention: 24h
        sync-interval: 1s
