---
- hosts: runners
  become: yes

  vars:
    github_runner_enabled: true
    github_runner_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    github_runner_version: "2.334.0"
    github_runner_base_dir: /home/deployer/github-runner
    github_runner_user: deployer
    github_runners:
      - name: "spanbarn-1"
        repo: "wiebe-xyz/spanbarn"
        labels: "build"
      - name: "spanbarn-2"
        repo: "wiebe-xyz/spanbarn"
        labels: "build"
      - name: "spanbarn-deploy-1"
        repo: "wiebe-xyz/spanbarn"
        labels: "deploy"

  roles:
    - github-runner
