[runners]
pxe-github-runners ansible_host=192.168.4.105 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa
germany ansible_host=193.24.209.222 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

[macos_runners]
mac-mini ansible_connection=local ansible_python_interpreter=/usr/bin/python3
mac-laptop ansible_connection=local ansible_python_interpreter=/usr/bin/python3
