package api

import (
	"fmt"
	"strings"
)

// writePromptInstrumentation writes the LLM prompt instrumentation guide.
func (g setupGuide) writePromptInstrumentation(b *strings.Builder) {
	fmt.Fprintf(b, "## LLM / Prompt Instrumentation\n\n")
	fmt.Fprintf(b, "SpanBarn tracks LLM calls as first-class spans using the [OpenTelemetry GenAI semantic conventions](https://opentelemetry.io/docs/specs/semconv/gen-ai/).\n")
	fmt.Fprintf(b, "Instrument your prompt calls to see them on the **Prompts** dashboard with cost, latency, token usage, and error tracking.\n\n")

	fmt.Fprintf(b, "### Required Span Attributes\n\n")
	fmt.Fprintf(b, "| Attribute | Example | Description |\n")
	fmt.Fprintf(b, "|-----------|---------|-------------|\n")
	fmt.Fprintf(b, "| `gen_ai.system` | `openai`, `anthropic`, `openrouter` | LLM provider (required — this is how SpanBarn identifies prompt spans) |\n")
	fmt.Fprintf(b, "| `gen_ai.request.model` | `claude-sonnet-4-20250514` | Model requested |\n")
	fmt.Fprintf(b, "| `gen_ai.response.model` | `claude-sonnet-4-20250514` | Model that actually responded |\n")
	fmt.Fprintf(b, "| `gen_ai.usage.input_tokens` | `1500` | Prompt token count |\n")
	fmt.Fprintf(b, "| `gen_ai.usage.output_tokens` | `350` | Completion token count |\n")
	fmt.Fprintf(b, "| `gen_ai.usage.cost` | `0.0042` | Cost in USD (optional — SpanBarn stores as-is) |\n")
	fmt.Fprintf(b, "| `gen_ai.request.temperature` | `0.7` | Sampling temperature |\n")
	fmt.Fprintf(b, "| `gen_ai.request.max_tokens` | `4096` | Max output tokens |\n")
	fmt.Fprintf(b, "| `gen_ai.response.finish_reasons` | `stop` | Why generation stopped |\n\n")

	fmt.Fprintf(b, "### Optional Attributes (Analytics)\n\n")
	fmt.Fprintf(b, "| Attribute | Example | Description |\n")
	fmt.Fprintf(b, "|-----------|---------|-------------|\n")
	fmt.Fprintf(b, "| `gen_ai.prompt.template` | `summarize-v2` | Template name for grouping/fingerprinting |\n")
	fmt.Fprintf(b, "| `gen_ai.outcome` | `success`, `failure`, `partial` | Business outcome of the prompt |\n")
	fmt.Fprintf(b, "| `gen_ai.quality_score` | `0.85` | Custom quality metric (0-1) |\n")
	fmt.Fprintf(b, "| `feature_flag.key` | `prompt-variant` | OpenFeature flag key (for A/B testing) |\n")
	fmt.Fprintf(b, "| `feature_flag.variant` | `concise` | Active variant |\n\n")

	fmt.Fprintf(b, "### Prompt/Response Bodies (Span Events)\n\n")
	fmt.Fprintf(b, "To capture full prompt and response text, add span events:\n\n")
	fmt.Fprintf(b, "```\n")
	fmt.Fprintf(b, "Event name: \"gen_ai.content.prompt\"     → body: the full prompt text\n")
	fmt.Fprintf(b, "Event name: \"gen_ai.content.completion\"  → body: the full response text\n")
	fmt.Fprintf(b, "```\n\n")

	fmt.Fprintf(b, "### Node.js / TypeScript — Anthropic SDK\n\n")
	fmt.Fprintf(b, "```typescript\n")
	fmt.Fprintf(b, "import Anthropic from '@anthropic-ai/sdk'\n")
	fmt.Fprintf(b, "import { trace, SpanStatusCode } from '@opentelemetry/api'\n\n")
	fmt.Fprintf(b, "const anthropic = new Anthropic()\n")
	fmt.Fprintf(b, "const tracer = trace.getTracer('%s')\n\n", g.slug)
	fmt.Fprintf(b, "async function chat(prompt: string) {\n")
	fmt.Fprintf(b, "  return tracer.startActiveSpan('chat', async (span) => {\n")
	fmt.Fprintf(b, "    span.setAttributes({\n")
	fmt.Fprintf(b, "      'gen_ai.system': 'anthropic',\n")
	fmt.Fprintf(b, "      'gen_ai.request.model': 'claude-sonnet-4-20250514',\n")
	fmt.Fprintf(b, "      'gen_ai.request.max_tokens': 1024,\n")
	fmt.Fprintf(b, "    })\n")
	fmt.Fprintf(b, "    span.addEvent('gen_ai.content.prompt', { 'gen_ai.content': prompt })\n\n")
	fmt.Fprintf(b, "    try {\n")
	fmt.Fprintf(b, "      const msg = await anthropic.messages.create({\n")
	fmt.Fprintf(b, "        model: 'claude-sonnet-4-20250514',\n")
	fmt.Fprintf(b, "        max_tokens: 1024,\n")
	fmt.Fprintf(b, "        messages: [{ role: 'user', content: prompt }],\n")
	fmt.Fprintf(b, "      })\n\n")
	fmt.Fprintf(b, "      const text = msg.content[0].type === 'text' ? msg.content[0].text : ''\n")
	fmt.Fprintf(b, "      span.setAttributes({\n")
	fmt.Fprintf(b, "        'gen_ai.response.model': msg.model,\n")
	fmt.Fprintf(b, "        'gen_ai.usage.input_tokens': msg.usage.input_tokens,\n")
	fmt.Fprintf(b, "        'gen_ai.usage.output_tokens': msg.usage.output_tokens,\n")
	fmt.Fprintf(b, "        'gen_ai.response.finish_reasons': msg.stop_reason ?? '',\n")
	fmt.Fprintf(b, "      })\n")
	fmt.Fprintf(b, "      span.addEvent('gen_ai.content.completion', { 'gen_ai.content': text })\n")
	fmt.Fprintf(b, "      return text\n")
	fmt.Fprintf(b, "    } catch (err) {\n")
	fmt.Fprintf(b, "      span.setStatus({ code: SpanStatusCode.ERROR, message: String(err) })\n")
	fmt.Fprintf(b, "      throw err\n")
	fmt.Fprintf(b, "    } finally {\n")
	fmt.Fprintf(b, "      span.end()\n")
	fmt.Fprintf(b, "    }\n")
	fmt.Fprintf(b, "  })\n")
	fmt.Fprintf(b, "}\n")
	fmt.Fprintf(b, "```\n\n")

	fmt.Fprintf(b, "### Node.js / TypeScript — OpenAI / OpenRouter SDK\n\n")
	fmt.Fprintf(b, "```typescript\n")
	fmt.Fprintf(b, "import OpenAI from 'openai'\n")
	fmt.Fprintf(b, "import { trace, SpanStatusCode } from '@opentelemetry/api'\n\n")
	fmt.Fprintf(b, "// For OpenRouter, set baseURL: 'https://openrouter.ai/api/v1'\n")
	fmt.Fprintf(b, "const openai = new OpenAI()\n")
	fmt.Fprintf(b, "const tracer = trace.getTracer('%s')\n\n", g.slug)
	fmt.Fprintf(b, "async function chat(prompt: string) {\n")
	fmt.Fprintf(b, "  return tracer.startActiveSpan('chat', async (span) => {\n")
	fmt.Fprintf(b, "    const model = 'gpt-4o'\n")
	fmt.Fprintf(b, "    span.setAttributes({\n")
	fmt.Fprintf(b, "      'gen_ai.system': 'openai', // or 'openrouter'\n")
	fmt.Fprintf(b, "      'gen_ai.request.model': model,\n")
	fmt.Fprintf(b, "    })\n")
	fmt.Fprintf(b, "    span.addEvent('gen_ai.content.prompt', { 'gen_ai.content': prompt })\n\n")
	fmt.Fprintf(b, "    try {\n")
	fmt.Fprintf(b, "      const res = await openai.chat.completions.create({\n")
	fmt.Fprintf(b, "        model,\n")
	fmt.Fprintf(b, "        messages: [{ role: 'user', content: prompt }],\n")
	fmt.Fprintf(b, "      })\n\n")
	fmt.Fprintf(b, "      const text = res.choices[0]?.message?.content ?? ''\n")
	fmt.Fprintf(b, "      span.setAttributes({\n")
	fmt.Fprintf(b, "        'gen_ai.response.model': res.model,\n")
	fmt.Fprintf(b, "        'gen_ai.usage.input_tokens': res.usage?.prompt_tokens ?? 0,\n")
	fmt.Fprintf(b, "        'gen_ai.usage.output_tokens': res.usage?.completion_tokens ?? 0,\n")
	fmt.Fprintf(b, "        'gen_ai.response.finish_reasons': res.choices[0]?.finish_reason ?? '',\n")
	fmt.Fprintf(b, "      })\n")
	fmt.Fprintf(b, "      span.addEvent('gen_ai.content.completion', { 'gen_ai.content': text })\n")
	fmt.Fprintf(b, "      return text\n")
	fmt.Fprintf(b, "    } catch (err) {\n")
	fmt.Fprintf(b, "      span.setStatus({ code: SpanStatusCode.ERROR, message: String(err) })\n")
	fmt.Fprintf(b, "      throw err\n")
	fmt.Fprintf(b, "    } finally {\n")
	fmt.Fprintf(b, "      span.end()\n")
	fmt.Fprintf(b, "    }\n")
	fmt.Fprintf(b, "  })\n")
	fmt.Fprintf(b, "}\n")
	fmt.Fprintf(b, "```\n\n")

	fmt.Fprintf(b, "### Python — Anthropic SDK\n\n")
	fmt.Fprintf(b, "```python\n")
	fmt.Fprintf(b, "import anthropic\n")
	fmt.Fprintf(b, "from opentelemetry import trace\n")
	fmt.Fprintf(b, "from opentelemetry.trace import StatusCode\n\n")
	fmt.Fprintf(b, "client = anthropic.Anthropic()\n")
	fmt.Fprintf(b, "tracer = trace.get_tracer(\"%s\")\n\n", g.slug)
	fmt.Fprintf(b, "def chat(prompt: str) -> str:\n")
	fmt.Fprintf(b, "    with tracer.start_as_current_span(\"chat\") as span:\n")
	fmt.Fprintf(b, "        span.set_attributes({\n")
	fmt.Fprintf(b, "            \"gen_ai.system\": \"anthropic\",\n")
	fmt.Fprintf(b, "            \"gen_ai.request.model\": \"claude-sonnet-4-20250514\",\n")
	fmt.Fprintf(b, "            \"gen_ai.request.max_tokens\": 1024,\n")
	fmt.Fprintf(b, "        })\n")
	fmt.Fprintf(b, "        span.add_event(\"gen_ai.content.prompt\", {\"gen_ai.content\": prompt})\n\n")
	fmt.Fprintf(b, "        try:\n")
	fmt.Fprintf(b, "            msg = client.messages.create(\n")
	fmt.Fprintf(b, "                model=\"claude-sonnet-4-20250514\",\n")
	fmt.Fprintf(b, "                max_tokens=1024,\n")
	fmt.Fprintf(b, "                messages=[{\"role\": \"user\", \"content\": prompt}],\n")
	fmt.Fprintf(b, "            )\n")
	fmt.Fprintf(b, "            text = msg.content[0].text if msg.content else \"\"\n")
	fmt.Fprintf(b, "            span.set_attributes({\n")
	fmt.Fprintf(b, "                \"gen_ai.response.model\": msg.model,\n")
	fmt.Fprintf(b, "                \"gen_ai.usage.input_tokens\": msg.usage.input_tokens,\n")
	fmt.Fprintf(b, "                \"gen_ai.usage.output_tokens\": msg.usage.output_tokens,\n")
	fmt.Fprintf(b, "                \"gen_ai.response.finish_reasons\": msg.stop_reason or \"\",\n")
	fmt.Fprintf(b, "            })\n")
	fmt.Fprintf(b, "            span.add_event(\"gen_ai.content.completion\", {\"gen_ai.content\": text})\n")
	fmt.Fprintf(b, "            return text\n")
	fmt.Fprintf(b, "        except Exception as e:\n")
	fmt.Fprintf(b, "            span.set_status(StatusCode.ERROR, str(e))\n")
	fmt.Fprintf(b, "            raise\n")
	fmt.Fprintf(b, "```\n\n")

	fmt.Fprintf(b, "### Outcome Tracking\n\n")
	fmt.Fprintf(b, "After evaluating an LLM response, annotate the span with outcome data so SpanBarn can correlate prompt changes with business results:\n\n")
	fmt.Fprintf(b, "```typescript\n")
	fmt.Fprintf(b, "// After checking the LLM's answer:\n")
	fmt.Fprintf(b, "span.setAttributes({\n")
	fmt.Fprintf(b, "  'gen_ai.outcome': 'success',       // or 'failure', 'partial'\n")
	fmt.Fprintf(b, "  'gen_ai.quality_score': 0.92,       // your own metric (0-1)\n")
	fmt.Fprintf(b, "})\n")
	fmt.Fprintf(b, "```\n\n")

	fmt.Fprintf(b, "### A/B Testing Prompts (with OpenFeature / FunnelBarn)\n\n")
	fmt.Fprintf(b, "If you use feature flags to vary prompts, set the flag attributes on the span:\n\n")
	fmt.Fprintf(b, "```typescript\n")
	fmt.Fprintf(b, "const variant = await featureClient.getStringValue('prompt-style', 'default')\n")
	fmt.Fprintf(b, "span.setAttributes({\n")
	fmt.Fprintf(b, "  'feature_flag.key': 'prompt-style',\n")
	fmt.Fprintf(b, "  'feature_flag.variant': variant,\n")
	fmt.Fprintf(b, "})\n")
	fmt.Fprintf(b, "// Then use `variant` to pick the prompt template.\n")
	fmt.Fprintf(b, "```\n\n")

	fmt.Fprintf(b, "SpanBarn's Prompts dashboard will group by variant so you can compare cost, latency, and outcome across prompt versions.\n\n---\n\n")

}
