apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spanbarn-production
resources:
  - namespace.yaml
  - ../base
  - ingress.yaml
images:
  - name: ghcr.io/wiebe-xyz/spanbarn/service
    newTag: local
  - name: ghcr.io/wiebe-xyz/spanbarn/web
    newTag: local
