apiVersion: ENC[AES256_GCM,data:kY0=,iv:mhILbxMz4UkbWReGwhFfaDCg3RDBti+de/io2qFnB8w=,tag:0xVjXU2ZJ7aLdMenNc9OfQ==,type:str]
kind: ENC[AES256_GCM,data:waIdRg5J,iv:zumQix+PT0a6EYGbbWcFxB7ZHLdpuMIv5wXzvNMWF7I=,tag:lLzqdumi/9pLB8rcb9zMVw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yvdzwlkTR5Nhy/yNt+setA==,iv:PpaZ8DBSHU7o8PGn++wZ4qVzw8hxmP/nECbdTk/3pH4=,tag:EIV0OL0tFZas1kiLz+KzBQ==,type:str]
    namespace: ENC[AES256_GCM,data:5EanZ0wkkUGRdZ3U0tTtCQ7Xjg==,iv:gfrlp1ALfX3jncrw5bQvF3i78M8ny9okJx/0pFzFzzo=,tag:JVI4dJayvPu50agPHsW6wA==,type:str]
type: ENC[AES256_GCM,data:VAYO4YK2,iv:MFctC/VF3UWU0VxIT4fqhY1Ipg/oIeXDFN4q4ycGZRI=,tag:YW7mPzyGdOIEVx+1GVjVPg==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:Y8SAlHLV4vzowpY5ND/ofB1JSARQicILj2M61GcWwoSQ2GhsVz6hjA==,iv:j4f9MHO4/EZMBRKlTFRbuVT66LAo+bgWBbiom4k469Q=,tag:iTdUMUQQ4asfuSwGP9veyg==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:YjiCimLY45ovBfFdg0KjDyZNf9fM+4b97cqm9StNYoehsZsaXnq3mHsU43BKFaOjB2pWXmwKCpEROTbOdgudhg==,iv:uGi21MeJxkrv/6WY0MQI51Lf38kN6C1teTZmW0GBIvY=,tag:cO9nktkaCprSybP5GIJl/g==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:5eJv9jdcMdfruOuufCCAjYz8Jh0y0h9k6fOc4QnCRvI5g7c1/EX3Eg==,iv:1NwU0JGwvCofJqHbGQ1JRkvFdQK3KQuVAPwP/cRhqsU=,tag:Ow8GmRnJt7/DSCJ0UTb7Rg==,type:str]
    SPANBARN_SELF_API_KEY: ENC[AES256_GCM,data:76XujKTDzc9Zz/vwKjsQ8PRpPI+oHc1zl20nY84A4urOXUiHERqz+Q==,iv:kWTPo2ynGbdwWgr02yBqc7+0uDpX49821acLCul7RpI=,tag:XeDg3KPYULO0f33zIKB2TQ==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:+VsRwQ3uNtozOQ==,iv:FMuqWizoF658rlqTv4ENnSjS3h/5656FBP1f0pTHgFY=,tag:8vfw1T3S3rXa0BX0VeT/cw==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:zPfbP9wcKo0+m1+QKaH3PWb0YSe4,iv:PbYx0spv+tPep2WScOX2N9WCzrwPKunHyRzV7NKiwQc=,tag:cZI4MNBGntYfNUw9GikA7Q==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MdwKnyv7ClfbMJmR1fVejv1SeNIC,iv:STHX1pBfvXeNxKoD1NSf7SPkxbMuvLCYq2OemsHjv6I=,tag:rrxZ1hD3ePF41iKezsslhw==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:P0n2B1/4J//cocx/LlD+zc9RSGq3,iv:gBsq1cYNX1tKB/hE7aN32kypKbKeQK6+aG7hKMKSa04=,tag:LrJh0lN5QiyaqWeJcORvlw==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweUFTdWtyMG1lSS9nTTg4
            Q0JSUUIzMHBDdlVVQUNCYVR3czhLV0pMcDBVCjhNVWRNY0k4N1hqZENoZGVzQ2hl
            UjREeCsrU0ZoY3Fsd1VkeGY2QkJ1RTAKLS0tIDZSOXpPWVZOZ2tmRWhNYytkL2JG
            S2VmNmlzTDh1cUVGOVNneVk2TWkxSWsKA5Je57gKFcbVooKP/XvCIbconT9GGiNq
            M/l5K7VPVgBsJv36k2AzfJ2LKRFDYuoBH+dPzO4RqS4rBf1hIv8bCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T07:21:39Z"
    mac: ENC[AES256_GCM,data:LQLzyECXWzUK/k7l3AI6xbx0gUVNCsSCsGub1GBxUb7kSkSBDL09K1vNmepGotBPrcaYsanVMkawZ1qevpMUAb2cGeKUUXuU8YPwaYIvhUTJ/t580qs85psvCIk0ELREcJcpNOsWgk6g1PzhzNm86IgkTlmH3vH06ftBvw3C77Q=,iv:c89I1aWMHr7EIl5YFxAF8P5ITSK5xgdQi34zbuIxfio=,tag:z272skpOZhZ41NwEKiHvgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
