apiVersion: ENC[AES256_GCM,data:u54=,iv:6x9iq4uDR0vbleSIJjXlW1UXcl3nK4InfeoJ49Qk8zA=,tag:E/PzRPF6yWK8FXWVPoScdg==,type:str]
kind: ENC[AES256_GCM,data:gnOTVgeb,iv:krVagDugbb85mcZI0RE5L8C98fSmbr0GCmRcjJhK4s0=,tag:BtYL8rNk8BEkRPWvHSyBIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i/eHocVdGhIP+lm8tmJwuQ==,iv:rBG9fsEsiZHEexOkY5GpcQLxpVDusWuaoVB9+skqJ5w=,tag:ZGIEP/u7Fhvb8FpJv5n4YQ==,type:str]
    namespace: ENC[AES256_GCM,data:KvpkXXwNX0mvBomUZ2f1YMt8ZA==,iv:aCJA0TZPbxIlppYwTedOou0R22z3Yp3KiZ/yx83H5Vk=,tag:SA89Pd3yxeONvFUSoBODag==,type:str]
type: ENC[AES256_GCM,data:kIQSyZhm,iv:rnKN3Pah/tuOmhkzWCtX/K4bqq48gf2ddAPBaXQlBYU=,tag:cCD0zVDIcedCY2zhYHYNgw==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:m/pscISGxbnYELf2/h2I2dtTlovouqjtDzOrEazGQ6vItu2CTT6QYQ==,iv:QT3dgAJPxRrtAity6pSxCZOGjZ2KMuDwaVruwTDvWbE=,tag:0VA5rO8EUW2YAlnAJY4a1A==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:Ikz8T/HnbKpZf04CdEkuDD4EznfOQufL16SfX6GlEnWSRG+LvQ+SI6X4Zs8kGdDrsRfLU+X4dZLjfd1zULXfUA==,iv:CaFxnwvCjcukmnuvtbB8fnt9HmZ6hGNH7zv3Bk+jF2Y=,tag:xEpXmlH88Oyki6QRaaHHvg==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:RzxJkN88gzSIUtpPY54SwWcmJ6Vd57CUEy8w8+sYHYIchBfY17Ue1g==,iv:srGYtUdeaGlLYpUs/b0AV6xiykSdD5Bi4VTcggccZHU=,tag:60ZbonfCcOk89ok4s+uk6w==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:sgjY9V9R9LQuEQ==,iv:dpARMVqXfyTaFC33PSA3mvi7AGgPj1uobwVCWvggTMM=,tag:3nlPyCFKgiAMFWrSX26LuA==,type:str]
    SPANBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:CNacd7E=,iv:RDhecuAAdrznLKE9KeNafczPUaxpYlk2/U77ppuGGT4=,tag:5DD6Nxi/lDtW0YU7Ewif1Q==,type:str]
    SPANBARN_ADMIN_PASSWORD: ENC[AES256_GCM,data:7SdepuElCr0=,iv:Xb6PfYt5HqPEw/IQUH6j7qax6uJtI6ryNwFd0IxA9sU=,tag:wvFaQrsOti+MYWUQfMl8eg==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:v78b2IBWCddWXdCwGzRhplXCAVry,iv:cuSgg3nvSRP0rxmcQ2RMLXaW5V0GzfK5qKN7Ys4i59g=,tag:e2p+lA8sRonCrcNXNWMr1g==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QIp96pHScHcOGax0zPKPBW9YZsh6,iv:LlRvDrIPqNgznprhydNr1LiJLRFMNQQDqyxG2gl9Z3E=,tag:36yVj8l9xVgorZDWPuoF5g==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:2K2b1HUNKeIbQ52rJ0Aw8kD3KNu6,iv:zsasSJagR9sNue4SRD1OjaqMyayLCqi4GBio2as/nc8=,tag:WOJJDYt+hl9GOAv90r7G5Q==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UmVVZnhPQ3dPYzE2UzB0
            NWdFeTA4ckE0UDRPWms3NW5IUVFoMmEwSGdFCmlndGpVSFpYK0paWXRnUU5OQU0v
            VytLbTQ4YmQzakZZeG1iRWtMTmpVcEkKLS0tIHl2ZWNhYXRaSnBWNkROb3pCY3lN
            eDlyOFBrRG8zL29ZZEtnZE9HWHNrWlkKor0kNewAOGeL1px/MI8f2S2ad6iL7qBD
            I2Of+Z2cjIdmgvLgwFhWYnSzzgC1+plFdTlM/CoVDdS+odu2zfEIlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T14:09:38Z"
    mac: ENC[AES256_GCM,data:AtuxIMWvjyuZZXsAqh/ObHk/RIRRaxZ+VdvmPMrER9iscRcDv9SJJYg+JDEdstOpjbS4FEvykRBRTwkDkiK0ve1wm9SxKGCsgaKEMHWh2iNvZ3h4O0VLvptPYXzYD8Tbq+kexp47P5SlbZeo9sQiyQEBmfevd+Rti0oVAMxWIWQ=,iv:4gBWyAhdFxp7jZLEyJItreVCoetcKK62eWzqPS3s9Ys=,tag:cLLZ93ldEs4sNQ3nNB/aDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
