apiVersion: ENC[AES256_GCM,data:ihw=,iv:aY56kODSms/TxCOJW7ctMcv4wNdixmkjLrSdfa+Pdus=,tag:7MnbUYYJ/8CPI8dNEOcYBQ==,type:str]
kind: ENC[AES256_GCM,data:eyVCQ8EU,iv:LfgAg/Avv7YU2pb5ZnHMCCqdNh+INUPlLWErHWf0Gck=,tag:KrerX/SNXQ0CpCwDTc9mHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qPkIaqtXa6TiCi1S5It/Bw==,iv:9Ys80lnWfwBdZANrDstSYq3aFq4UT6G550mPWwxqYpI=,tag:jVQhG/1Xa9QBhH7rAKxKvA==,type:str]
    namespace: ENC[AES256_GCM,data:2W1d7PhbB47eYF4tqQxijAyrzQ==,iv:Vg46/F/+ic/vwqmCxwHhOYonw0TZrINaSZqLnSNeafI=,tag:UW5Ke2f3CoRJ3tjRWnXO1Q==,type:str]
type: ENC[AES256_GCM,data:fvyEgDjJ,iv:GiQY1Ygpr5AkNnUHRAb87+Pz9M1+MPsQvmS4k1/C1AE=,tag:q5YyY1J+ZY2RK8d++dz4RQ==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:ScsvN10rzieYwyq5SAYE4/+u/ssK4j023yhMQHEzH6ZYAH8uPyIeWA==,iv:Z4tyE/S6sjyJGRk0mLUvtxdVTwabxhX1GIqejFFDuCo=,tag:bIfq7r3X6qPvV08HaQmmug==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:igoeXCVMiwTTZ5ZwE/D/KnhuNaF2VV7hhRCdjt0I1VBVj9NugjgcfFw/EJbdAM7GkCFpmj9IizmPNSlaNGdOdQ==,iv:6hTAd4TNqvEcFUaa2HdxjDoeo+8MwxClKATuKrOrmBA=,tag:QDXSlrY7RQh6elE++gsPLg==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:rvJr35ct8CMV0ofCK57AhP9/l1tMtqhi4O47uFZYquiRhS2ZMaFuZA==,iv:jsRZPxKlk9/lbY5dQ7OYg6DWAEgOg9nP2VvlJe0bbAA=,tag:W/rBlfVQnRYwwXoShRpuQA==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:RKkwYuNJ5Xfmfw==,iv:DRN2++C5aObz837QJi5Sc+DEBK6fOvTpZ5SXqquYWlA=,tag:uCfAnqqSpcJIL5rU7te5lA==,type:str]
    SPANBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:9Y+7UlA=,iv:AXrWFZPuV89yA6Z4t5XpVdgj+CiUgK+wW7+Aeyo0K9I=,tag:6Iegup1uBxpq7SOUpM5/Zw==,type:str]
    SPANBARN_ADMIN_PASSWORD: ENC[AES256_GCM,data:NGC4poO5dZE=,iv:BzBZXi6KdKKFGv6gcmgt6yGWBw0ZQHrxmWiPnZDekeI=,tag:K9wfmD6UrMlmZli3zUPFSA==,type:str]
    SPANBARN_SELF_API_KEY: ENC[AES256_GCM,data:MdMUiK5ts8wK/Psy8jCY+nC5UjW3fzWntmxvTKtUDaDA8wqcQibDyQ==,iv:/J3iMPMrbWg9pva9sGmbWbU4hK40oBc8BM8N0R2zBsI=,tag:5XQySI1jNkQ5yJsQ4KcSXw==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:jM20n0XqmsQ2wwpmvA==,iv:UcUUl4LWPIvHizGNI7a8QPO/Jtt80k7tML2MCE7gOms=,tag:6lq35hT88H17PhlSDi7Few==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Dbkzv1wqjWC0k8LOAEDQr3fCsGLaZlgfRakaIYNCAJ1WT02iXZb0uA==,iv:n4wv+IPTUOGD7orE1zVlEWnVhd06qWRep9W8lhYKR3E=,tag:HEsYDi6S5mt6LNe5FvY48A==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:zliUmcsRrrZosg==,iv:4gYRVpT70/N37pyh0eut9Yj6NkULKzqiKVuCovRj3u4=,tag:S7zVkudg2rjMPz1P5coWWw==,type:str]
    SPANBARN_FUNNELBARN_ENDPOINT: ENC[AES256_GCM,data:HwNgHUUYQWDZbOkvf+dIu78u+r/n6QMlDBKoiQ==,iv:4aV+qBP9+080KDePZCcEKC5ibLkRCsEst9jWePASMMc=,tag:LaMg+njHse/LlKLlbFctjg==,type:str]
    SPANBARN_FUNNELBARN_API_KEY: ENC[AES256_GCM,data:NzfEXAgvLmhu91duv7RNf3yCOWCrO7ZnCTaQHavttue7l6PwEUMA0Q==,iv:1J3oijSev45KGhiyKXUJQ3MFuSAQ8LmUkfI9WublE4M=,tag:OWPTf+RT3SqjzU8R7pyrAg==,type:str]
    SPANBARN_FUNNELBARN_PROJECT: ENC[AES256_GCM,data:e94Ys2daiPQ=,iv:oeTSIaA2P4XN0ldC7V+6cX0tkYbbucBDqNr3DWLdbh4=,tag:3CvpuWycQ2lw7G6+eb++8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTjBaYm9vN2p6dUpaQTg3
            dVZBYmlNTUliQkNLbWpXelcvdU9TSWZ5djBnCit2MTlMdG8xNURhdFRia0JzVk1n
            Q0l0NWJucWQ0QjVDSy9wSFRhdDNYNHcKLS0tICtEZE1ISzcra0RmVTRjQlRrVDY5
            elo4cko3b01ZdTViOC9zNk5KZFY4RjgKlc1P892HWbmiCQ1iD+l0LXD4JDjmxJzN
            ppLLPXz3vwKSirpHk5wVQ2NAPKL28G+8Hcz2LaoXXO0akhxqRHxSiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T15:09:12Z"
    mac: ENC[AES256_GCM,data:TSW/gFKEPDPenk36kOHxlks+a+IuomyPxGtDq3cM01uhlYhY/62LZl/R2JYyT6QMFv5tG5n4HNkhLBHmnwhfMtxu1DJ1GNG0h2CoQOK3NwKo4NNjyzafan5uz+oYYAGdcqjK3u37VoaAJJkd2i+IveLSgEvjjfZHJxrO/YD7Zqk=,iv:4oeNGUVgUldzp/+KDqIggpM3swaCsVYcS4qF4WYN85g=,tag:eQNge/1lEoW7z+APXoGH8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.12.2
