#ENC[AES256_GCM,data:66NCmpN6m0LUpe3GUctMNbPdOmO8XKpgx6a4uYEUvJHE3VS1bTq1pj2N0ri++UnOY0Oev0SVaVu1YVVBew==,iv:FTeo4JcqMI0U1UTZgjBoFGjJLWGdgaerjxVPlhEx5xI=,tag:uDMw8sxShXCatb/AVlSAbQ==,type:comment]
npm:
    token: ENC[AES256_GCM,data:qfm+8J7cCBco6aq9X2vfeoCkPQoIOxP90qnVcjTTPOPJxcJl5TEEug==,iv:gopSnSwuB2iQVUgTe2FyBELW4RhUXR1+Jg9Y7ulPWqA=,tag:ZL464A5TiSNh9mACmekQbg==,type:str]
pypi:
    token: ENC[AES256_GCM,data:E3S/SCC3uKYCY9qMoMlR66BLrXeOLM0/iN2V95oz61GffmVBFpJFoRAC9v5Somxl48UOm2skfxXmArjVPBNqxFwH/EcCrRkXMn7z5vx2QkI32rnjTcjH0MWQ1wjFqjHZHJMvyU0SprFUhts+x6X7Nxjyz58/wmQmGEYaQ3F3JM6lwslhzgy7IQInKyhuMAdfljBFn80TJ2xT184S4RnXrmuiHNTgu3k9wDj06xqUd9bAdjw=,iv:PpBXkbGW6b52BtznxSO3037BPwLD7A+rYvstuZAsCq0=,tag:C/KpXesEzfxEDqBj47Nd0w==,type:str]
github:
    release_tag_pat: ENC[AES256_GCM,data:9XI/O7FwotbVpohApnQ+pCqMnVE3wqyZ6ym1UnFhfj2YPn1v6zWOkw==,iv:M5aKFIOdfolfa4PxLVVu/GxaGVX3Au5CosDEGzfkPT0=,tag:kQiDfrr+i9Y/hRwJhi5wBQ==,type:str]
r2:
    access_key: ENC[AES256_GCM,data:Knv3TifKfTV1IP6XUU0W/uLhpYt+wX5Zy7X77IHUSWo=,iv:KCV1jDBZRm2UGV2i/KZKvWVrERSTgQcDDRFw2A2fzs0=,tag:gkaoL2Cb7XpsMindbMXbbQ==,type:str]
    secret_key: ENC[AES256_GCM,data:REJQcM63mNewN5LB9arEg9bNyknNcje7tgqO2Zx2/QrRqmWqT4CwlOrnsSS5Id8eJnqkiYN+8BGLam6vzh1hxA==,iv:KoTFokb+iqlzBy5sF6sdIu1QRL/XmwffC1DADUPNX7Y=,tag:7hgAmDSZa6mVeEKJg5zvwg==,type:str]
    endpoint: ENC[AES256_GCM,data:lqKYXGzlYc6J5uhusniNXyopqladWY0kA2IGHUi9kiOOKzkAV/Otaqp34vxM5DVvrC5W3OQRZx6H0kzH5HZHjq1pSvA=,iv:A9J58Iuo/hwHS4cvpH2mffMuu/YU2tmX351S/GWQ46o=,tag:BmSoC5oOGP9iJMy72JpNTA==,type:str]
    bucket: ENC[AES256_GCM,data:6TaqY+CkMKki5rtt8Kq5dwhqKyfAqrzGss5fwHafmRAvbA==,iv:Oe7FBUTIrbLToyZiticC5S1RGtCckwLSli71DKJY69U=,tag:wgmNued7U7XBfoM2CRaKUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSEY0eWdsajhFWkttLzUw
            VDVQeVEzVVhWVVRpWnlVZzlWRTl2S3VMM1NBCjcrYTRwTVM3OHJnUzNpei9BMStP
            Tjk3TVZ0RFB3N0hGZmF3amxGb1U1NTQKLS0tIE1WOENJZGhBU0RxRUVDU05SNzZI
            bUxVK01xR3VCNEEwYzBqMnVvZmE2NjQKLL9MbTRwWyp/auRXeWytQR29W/Exbi9Y
            fDXC0Ob8zoMLpzMmCdHfP4filAWuMY/COXQj1PH6MPJolw+/dliuog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
    lastmodified: "2026-10-01T09:12:47Z"
    mac: ENC[AES256_GCM,data:L70Vg9bLIB/oG8GoMsX29Kcy/cartPbGju74b5Kz8XQAQGerM5EJvgRckzelJx4Ynufc1GLKdM5hyep4XhuVzT0QXhsLBlfhQTeELrVgOoDE+q0zxxc3TPzIAMDAnxwP8My237di0wyTyzTPxb8SsURNDaHx/LM6h6puAKPiL40=,iv:78zJClPVKNmSqLU7fNRdAdcmv+9YN/AOWSKszntbYls=,tag:UM5ntu8JFiHsbthZF+JIgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
