apiVersion: ENC[AES256_GCM,data:io0=,iv:PDQSdgHFzxzcsJToo3ED+QIdQyPI1hJcvf7l7/zMQv0=,tag:wIE56cyPG0Of1gCkfjXUJA==,type:str]
kind: ENC[AES256_GCM,data:j+7b4lOb,iv:zzrjMaOUcOoIfg85bzIMFtsRW3g16cODP1gIa+5qWpA=,tag:VHLx59SUwG5/SgqblTnctA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1+qEAyyeKNd5Gnml4VzNefOKtVGVXLeS,iv:hEQFMzpQ7VminyqTPzN9I4HCWj8MtVobPcS6z+NPkBM=,tag:IL142l3eM+VQ5y0Gq9IsIA==,type:str]
    namespace: ENC[AES256_GCM,data:Rg+PdM9v31gz1CKGmjaeSg==,iv:PRQog4/cjgRkvR+WafwDu7fbbYQSdsKY9FvV1BEMMCw=,tag:mN0vvS/Lkfq8OZq3Eb5ebw==,type:str]
type: ENC[AES256_GCM,data:AB/HBKc2,iv:85sCz+1nXtU/PQyUrHYBs/0uGfG877RpfTr7zQ7BpvE=,tag:6VjSNWc7K+fVI62sZd6M2Q==,type:str]
stringData:
    E2E_IAMBARN_EMAIL: ENC[AES256_GCM,data:KMNjg8RPlN8FDz7rBPJN,iv:C0fzOx/WbcoMCC+k8HF/4vbx5P64I0kXTLwCEHQC8og=,tag:1imGLkoXnBYl+5ItKuU9og==,type:str]
    E2E_IAMBARN_PASSWORD: ENC[AES256_GCM,data:dGuajir62F4=,iv:dyJQi8/+QTd51JFETW8Vu8g3CfJCYMmmGT2zbaQTxdM=,tag:HnTRkPWarrpbuu/Yop0Acg==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQVZnME9PbUJrelVrdWxp
            ODZxUC9XQ3cvL0dGMDVNN20vUHpHd1hOZW1NCkE3OXlOalBLdmNNZHA3UWYvY0l5
            bnp6ZzdFL2JFYmcwVzFURVJYbnVsVmsKLS0tIEx2b1dTVk5FL3EyelpVc0Zab1l2
            YW5xWURDakh3dzFucHFoODRkckVvRWMKB8wO9y3I32swvkW9EVNhlWr/MoNisENO
            AmrbeTf20QlSTPENjhqtJbP1gY0iPNHT1IWun1A+7McWMpiAGGs+ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T10:04:09Z"
    mac: ENC[AES256_GCM,data:qRhk5kpUAQ52ZIGNmLZ3sBlraR2uPtIZey3R3UNmkfXfNhiCyhzJEcl8p3Qo0KXz9ri+/XjUBXUdMcgJappSFI8GslOZGYtkcbH+HnN8gf4wN//iwCHIeUnvsw9EHGCBGRPkUPKdsMpc+PPUW0iPFjGyIYg7EuKAWivtqpxHztg=,iv:LfX3VyRLNzVqYNskTuNETymv141/Itjq6bY2rynNW1E=,tag:vS01qe7SxuE7nFPO2SQZpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
