apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spanbarn-testing
resources:
  - namespace.yaml
  - ../base
  - ingress.yaml
patches:
  - path: writer-resources-patch.yaml
    target:
      kind: Deployment
      name: spanbarn

images:
  - name: ghcr.io/wiebe-xyz/spanbarn/service
    newTag: __SHA__
  - name: ghcr.io/wiebe-xyz/spanbarn/web
    newTag: __SHA__
