apiVersion: ENC[AES256_GCM,data:Te4=,iv:tScgIyONbDDDFCrq8zFPqqpJBLqko3ca+rwJf80MBPM=,tag:X7zt5JDFC5XnhFwM4H/9BQ==,type:str]
kind: ENC[AES256_GCM,data:pN7n+OED,iv:KgSaGUTaxkCoAXk6RoBj83pMj1HivOPyZzaIskBg+FQ=,tag:ivCqWuu6VCvKXIsD5wVIEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kKJM4nJQQAW87k26PwU6AA==,iv:fk3vJGoP/IxYXSHu0SxACyliNbqDMInY3sb4iaUDdnU=,tag:3pDklaj+ri/hXGvC4wuTDA==,type:str]
    namespace: ENC[AES256_GCM,data:F9XJT2jk2Ut4VXSnCoZtuQ==,iv:FK7Xw4i00rsXIMFwXj7w5srVWpOdQByJ2IyLtjQ5+UQ=,tag:RToaAWLZMjdjadLoFeItag==,type:str]
type: ENC[AES256_GCM,data:YfWTGRfB,iv:7ATo+iMAnkoXI3bkLmqWsr5WKqJaChkcBFPQrWkJA7Q=,tag:xd9ubfop/I019Fz52Vw9oQ==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:DDCV8ZJIhhAd5T1/wLiDortUDQZ9PbpQWe6heyzT+Mhh1gcjaqFsZQ==,iv:JBlWUKSxb4TpclZGuI4CiL0DjRdOG7fEj8utDxvPDg0=,tag:C7zz01kpK2DQFG7hdmP5Jw==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:/ufJUQtmN2PNXzMW8GD0lBrvcoFAel5uUzqGAvePaV1UROgfIAOsXBOfeF5tQO1LOmR2wrS9FxxCsqkW8jdubQ==,iv:49a/FKyT/1tfnmJl1F4JzQjNXkHegKmZSbFZ62Xdzig=,tag:u/+qMPlxKSROnu18T/F5xQ==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:yhWB6DRX8AoE/aEmbmbzDCDez5MX7oR4xYFodwrLWx6kQojFq+bhiA==,iv:kttq/T650QDW200XN6+UqfT1hEy/EX69UOhfWprIqVo=,tag:CC6EqkYMKidUIwN52Pu6Ag==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:BU/m+TCqIQ==,iv:2qaINE5MUI2K0h9v9bD9/x9yPlozkf6U59Xwp+E3fJo=,tag:LifQG7qfwS6xpZHo62nTOw==,type:str]
    SPANBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:K9MNb8M=,iv:OPpb4H6A69c/+ntore3/YyxWGjOuSvk4UAK2LYU8ZEo=,tag:J64RuFhndNrKI5QIJvD7/A==,type:str]
    SPANBARN_ADMIN_PASSWORD: ENC[AES256_GCM,data:jY2FsbfDbhs=,iv:ItEIc5ywvZWDzOMLWwNoxImA1bCJGmJ4HZXfm8d+Lr4=,tag:MpfkuraCqAXPwOkDfvGVeA==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:C0Ieasg2zVprMO1rybn5A3FBay+a,iv:xSrJw55qqLTbW0BL88gjfEOrMmkI2AnfnWrfhl78d50=,tag:/P7wGcFPgvBFDnDWCmirmQ==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iXy2nqXGalXEmTRmaynYOrE6GWqE,iv:8VJyT4Hh/9CHIJUFemTw2m3i/V1sFmO3vacq7RrTt1o=,tag:3xSSx+sUGkfWLceVYCq5CQ==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:44G3bO0bgKkUAI3o4dqVAFhXVZZ6,iv:658FCrMUwBvHvI0vv8r0IR0XlGoeqTDxCC6LsM34iaM=,tag:7QXayVBT6l/Akg57C1EJSQ==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y29XYUdnNHdzZlhxU203
            VlBobk5LU0VpSnArOFVkVjJnaHlLeHpkOWpJCkRDeFRDcGM1QUg1VUxUanM4d0VM
            YVhNcngwbXdpbXVYb0J5V202bnFCL2cKLS0tIEpwaWVMOWF2bUZ5YjBzSnhoNTZn
            K0tidDJjR0FnVDFHUk5JcUdnazlvaGcKDYR+MZ+IaWCopVzDR7GLdcGGB0FQfBb7
            zMEEqScFJOopEc1BA9u1AuFa15wWmHxnBAIAFo16yTKDSqkY0/dd7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T14:09:29Z"
    mac: ENC[AES256_GCM,data:4foEJha4i5r+aFEkDv54kTbFBcm/3krxrIxTEsNbKAk3MPrMe2KCt52lqIyE8nznlbH/xwaRQe6tYLOfegwRppJP4GLmNzz0O26IWF/i3NwB4eAjzTGHsnmuDoHWljVIFA6h6icwLxC/VopQ2Jo6S/yziTwv1RVAtstDTE/UMYM=,iv:Zp/7QaobTev3WRtpxKoJz3/vv8ACJtiOyDoxI3kaKD0=,tag:7DKU/tEgsZE+o/tDqXC5Bw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
