apiVersion: ENC[AES256_GCM,data:Vlw=,iv:hfLT3d1qeAUCjxGRzPMC1YN5/L3SPuDIaX6vaugU41k=,tag:o5bEJelfgshpVG/nLjFWsw==,type:str]
kind: ENC[AES256_GCM,data:09oQtLV7,iv:NFWWfIuwD8uxhK7OsWxDkiF8oXTvRrCgicCIEWWhtxM=,tag:wctJRndiKNteL4Bp0F+6AA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uoblEGX2VrgNtDNrafKkxA==,iv:0XOHj3sQ3UXzd/44bbKI0jycWPJ/Y9JYXtb7LnARcts=,tag:dS3xamWxjRMn7Bub1VpIyQ==,type:str]
    namespace: ENC[AES256_GCM,data:Cfe73wnvXcrm5CuZI6VO+w==,iv:OMyb1yVE+l/2Fq17LnX+krWzccJnAdmtRZQk6m/CT2Y=,tag:YOlJFhTKSj4VtffzaCEQWw==,type:str]
type: ENC[AES256_GCM,data:0VylXneq,iv:nu5OdzktnFZqSEfBXeGi3KJbsu+6cyPzAizKG4ke9B4=,tag:Cax2dU3QRDs4TafIvwQqHw==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:2Ac6QH+zhhucN+DIy58XQga3+tLzk14LuCIReDqK/ngfL1fP93Hc6w==,iv:I5zAiH/jGEsjO7dP8GJo5bKSDKGo2QC6trnWgpbW6Tw=,tag:9Z4vY6Xh7JqNYWXkpiEq7Q==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:h7C7pKtGZbxBJ4Pz7PB7dA4RQTiQXQUypANZ4V/FgZLRUrR+qK4aat3OP97C/thIAMchH0fmvLsZHRS6s9SwpA==,iv:f9QfAxileABPNoSPkyOLA+U4s9WSgvEITu4uJtv+yDk=,tag:4JXA9g4OTtXx3toQ0tnVBA==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:Xm+plEuQGNt7tJOQ1Mtv1bB99vmHTnce4/T68p0xhHr60Jd/wPbsVg==,iv:ZwDG1ryqyqlnjSg99piDNpuAacK3hbHWRfxxvVogCaI=,tag:O1697r53lVh+4ic17yisZw==,type:str]
    SPANBARN_SELF_API_KEY: ENC[AES256_GCM,data:v8cT4U3mK33Op2EV/7HRoVe3CSFqfEChsC2V5IvDDOGXqmtHF41cXw==,iv:dui+38cPe5kifwM2xRE9uxZPaTaLsToEnfkTpvwJud8=,tag:6RNdPcxwNpWD/fHqRIgaMQ==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:t9cBosKBDg==,iv:f33ZpXX4zlI0HZt39xGUHqkUwTQ8J5Vk9WdzHxiT3Fk=,tag:adACtpvn9cvftwduCaUWSA==,type:str]
    SPANBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:thwUWwY=,iv:OtTdW0atITfzcHu169OSpuopZ0az45a6DgQnuXVG9ro=,tag:bxMPthn0W+SVL97Lkie2kQ==,type:str]
    SPANBARN_ADMIN_PASSWORD: ENC[AES256_GCM,data:OCj6/k3K9O4=,iv:rVq8ARBbbEzN2pDjZRjiv6D6XWZHD6G5jxTjmhSPE4w=,tag:naZE70XAagZLTrYJ+wDv1g==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:F57M7q/MFqVFTH1GLrMN2rJuIOGv,iv:pOmXZ/5hu6WEC0tYv7PdSzDklNIDJGXIVyaFORkiDGA=,tag:Yv+Yh4LpnWlGqnBfxJoEtw==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:A3JY2HQmTSqCUg+dFD+lPuQVHGiH,iv:9N4olT60UamlOSNRS+u+jvYLWVd27amE7DsBeuIszEQ=,tag:JItAVJd+BvjwyzCSFTEDMg==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:Ipgbh5p66eMe80yUT0zB3N2+6U7V,iv:XUI+LBOi1J2ltvHXt8hnChGkwSyvmExSumH4IQvAmjY=,tag:4oNHf6VV+haZawYhGcOCEA==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURXQyL1BmTzFYc09yQmJI
            WG83VDB4eTJDK25ZNnkzUGNzQVZHV0t1ZFJJCllPY0M4RTZkd3A2Y2tlTWN6MUpG
            eWxDUDNkVzFEb3BRUjRuaVZpWUZ6ZUUKLS0tIG1qcW5IUzc1VllsbXh4SzlMRVlU
            MWZoOUl0WHJNTjJuckc3ZjJWK3Z0TjgK2Vc+ZAzNh6PSggMy1LNx3Na/oLCVTvdL
            ZdviFtpM7N+wUmk0CrB5cf20uDvgj5aeFZaud9zkB+cRgBByI+7e5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T09:30:03Z"
    mac: ENC[AES256_GCM,data:rEid38LZYHU7cxQM87W8VTufRRVPhRgEpTiB9BpqwjtL6gXHBY2HhcCoCboa/tPqqEEsmJ4sJ91EC1wUU5oF/L1GA7ibBTHcguhcIONOeOTG8k8dF0hCXP6l56yOdwQgPDxBYVoOfxy11L/US1jHP0ap3gvaqhDlV2HDVKLRkD8=,iv:AedT4KP8i8FwNnsxv0XW1pfTlp9Ddn7fDp/rweh588E=,tag:BWet+yYv94Mt4owfBZAN+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
