apiVersion: ENC[AES256_GCM,data:LoQ=,iv:ro66ghLqrp64j0vptGtVwGIfWRxIzdjTwgRZKjXU1vU=,tag:OGAyPX9KCbN2w/u620u3Aw==,type:str]
kind: ENC[AES256_GCM,data:BUkkIvOS,iv:j7ES5Jyj50/6I6kjRJO323uJam+PMQgmpo69c6bOG0A=,tag:HQpWht6tyMnMnlMOG+s8sw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jJ0+sFBCv4zbYY1oE/GkpA==,iv:kC4Gwy3mWjDlVJioBlh2XDaUis3CSzLRmsI1bcUR128=,tag:LQ3zUoJq9HMC/jPDmcUqTQ==,type:str]
    namespace: ENC[AES256_GCM,data:ws9xf/hbU36Gy4fL5rZmaQ==,iv:b+5MH2xwvYJh2tsCoibf2lVCR7My16V6Li+RjYdfh8o=,tag:CXXXDCH/L5d0Qz4WP9GgCQ==,type:str]
type: ENC[AES256_GCM,data:70Rj0dVB,iv:DlQnWheJx0MB9/gYT/QRrrErl8YzDyRHCHOTFUQzgY4=,tag:3qZ+0P1In4MGgShzyPdMew==,type:str]
stringData:
    SPANBARN_API_KEY: ENC[AES256_GCM,data:VxxQUgN4MrmOf1zxfqGvd0W4tDQz15J5fOqYw5eQ/Txw+MatHzfIcA==,iv:CTD9lng2M405t06sc04ZNywGRkziO7JfDy/Gf7JgaHM=,tag:wCUmXBR45vBK38rL8QeKuw==,type:str]
    SPANBARN_SESSION_SECRET: ENC[AES256_GCM,data:U8it3fxsUcRepbSUtYnXvRSEK/jJMQRs55mYzbH/gDoIGvZ/visF/0VZi8DLI5iJDceI14yLW48Irlpf5xRGfQ==,iv:oFs++805CN7SoXc9Vpw/vgBVx0gWijkQGottXK3BkC4=,tag:QwGFy9P9zgaDOapuKGkvmg==,type:str]
    SPANBARN_BUGBARN_API_KEY: ENC[AES256_GCM,data:tYKHAYQBRoGAKJEhZ72iagvLoQWKDG4Yt0oKbzWgsrqgzf7U46rx3g==,iv:eHCrdXriQRBeDpRuyxJIfz0zJRZJvJANQuQH12r+YEI=,tag:QFv8BxkD0JISPR55/tyk1w==,type:str]
    SPANBARN_SELF_API_KEY: ENC[AES256_GCM,data:IRdVK/LvqfZR+7Pf89O0YwQJ6xJdicUWuhejy4nMjVpfJ5dyskEiUQ==,iv:65GsUIiAFYwiy7nwGPtWFb2TM4a+9BfmNiFy1tdy6ug=,tag:3K04sh7kGy8sKARClclS9Q==,type:str]
    SPANBARN_ENVIRONMENT: ENC[AES256_GCM,data:LS/XdfRuBQ==,iv:7j3f99XM/4fYYcvHVPar/FGNfxSzhuI8xVTfrC+WDqU=,tag:+qmfiZxqA1GLeU0q+8kXZA==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:KxOZyBu63x160DUj2La1sDe6Swvh,iv:+SEm3NZiiW8ncvq2gfnNKB1V5KBaoY67efpXWclCYpk=,tag:sRUoCWLzkhQtblrGgLGeog==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dTPwc3mBRJaJ0CdHyf1oFIJ4lKQO,iv:B2zYo10pdU+dK6I12aoe1O+fRbQmdkuVBA8Xo7BIuG8=,tag:kv5+Hf4KRk4J05MW5me5qg==,type:str]
    LITESTREAM_REPLICA_PATH: ENC[AES256_GCM,data:x+ro5uhN5w/Z+BFE2RUjEuuxnwT5,iv:SN703s74l/ao+/NGZgzoHUDFWXnU9+t9YdEsLLmCm20=,tag:0MOm3rPs62fJA8j0EaJRPQ==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eW5SVHB2dFYweDlmcmJa
            SmE2RTBsS2dGUHFkZkdCTHd4Q3ZGSXB3MXo4ClJYQkYrTHlCaHdPTXhHV2U1Q0lj
            Nmt1RGhPWStiZnMrVG9YeEJkNW0rYzQKLS0tIE9ybWEydHVuQWx1enJnbnFHUDVG
            a2ZmVEFmZmlkbnVybmVOZ3R3bjU0UU0KYMO+qyxumlqI26OUChI2YJSwy5+FsX47
            dY9UNuxIn51Q+hSzuYOmSzNqYabZMVCikD/qeWJAUp9L3COggZgnsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T07:21:39Z"
    mac: ENC[AES256_GCM,data:e6M8IW75IIdskjR8V5M1nNNpFHEdVbkWhL4beWGVQCdsZT74IXeRhuKOWMoJ9rBGWlhZqSrJKTlmXXlckrKcVyjz1Mj7SpSpn+1zDWP1v8gMEENhiCHov4yxJyTvK/CBlI+Q22DhBdXDzdcGVlLHojZvt6E6KYUVutyKAXhbOC8=,iv:7lUlDPkckJaQcjnflIth2sRcdQ0Ie7WOKAMIwFJ2m1o=,tag:tyubDD/BlYwTtKNwJw/Prw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
